CREATE DATABASE TO_DO_LIST;

USE TO_DO_LIST;

CREATE TABLE TDL_USERS (
    USR_ID INT NOT NULL AUTO_INCREMENT,
    USR_NAME VARCHAR(120) NOT NULL,
    USR_EMAIL VARCHAR(60) NOT NULL,
    USR_PASSWORD VARCHAR(20) NOT NULL,
    PRIMARY KEY (USR_ID)
);


CREATE TABLE TDL_ITENS (
    ITS_ID INT NOT NULL AUTO_INCREMENT,
    ITS_NAME VARCHAR(20) NOT NULL,
    ITS_USR_ID INT,
    PRIMARY KEY (ITS_ID),
    FOREIGN KEY (ITS_USR_ID) REFERENCES TDL_USERS (USR_ID)
);